apiVersion: apps/v1
kind: Deployment
metadata:
  name: sso-client
  labels:
    app: sso-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sso-client
  template:
    metadata:
      labels:
        app: sso-client
    spec:
      containers:
      - name: sso-client
        image: sso-client:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: sso-client-service
spec:
  selector:
    app: sso-client
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
